name: Satsails
description: "Sail your wealth to the cloud!"
publish_to: 'none'
version: 2.2.2+129

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Functionality & State Management
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  rxdart: ^0.28.0
  i18n_extension: ^15.0.5

  # Backend & Services
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_crashlytics: ^5.0.0
  flutter_dotenv: ^5.2.1
  web_socket_channel: ^3.0.3
  coingecko_api: ^2.0.1
  crisp_chat: ^2.4.0

  # Breez SDK
  flutter_breez_liquid:
    git:
      url: https://github.com/breez/breez-sdk-liquid-flutter
      ref: v0.11.4

  # Bitcoin & Liquid Libraries
  bdk_flutter:
    git:
      url: https://github.com/StaxoLotl/bdk-flutter.git
      ref: refactor/cargokit-update
  lwk:
    git:
      url: https://github.com/StaxoLotl/lwk-dart
      ref: refactor/cargokit-update

  bip39: ^1.0.6
  bitcoin_message_signer: ^1.0.2

  # Local Storage & Permissions
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  local_auth: ^2.3.0
  permission_handler: ^12.0.1

  # UI & UX Components
  flutter_screenutil: ^5.9.3
  overlay_support: ^2.1.0
  dot_navigation_bar: ^1.0.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  pull_to_refresh_flutter3: ^2.0.2
  action_slider: ^0.7.0
  calendar_date_picker2: ^2.0.1
  msh_checkbox: ^2.0.1
  icons_plus: ^5.0.0
  loading_animation_widget: ^1.3.0

  # Device & System Interaction
  webview_flutter: ^4.13.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  vibration: ^3.1.3
  share_plus: ^11.0.0
  flutter_svg: ^2.2.0
  in_app_review: ^2.0.10
  upgrader: ^11.4.0
  app_settings: ^6.1.1
  flutter_keyboard_visibility: ^6.0.0

  # Data & Formatting
  decimal: ^3.2.4
  forex_currency_conversion: ^0.9.1
  currency_formatter: ^2.3.0
  fl_chart: ^1.1.0
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.4

  # Local Notifications
  flutter_local_notifications: ^19.4.0

#fixing fl chart for iphone
dependency_overrides:
  vector_math: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation & Build Tools
  flutter_launcher_icons: ^0.14.4
  android_notification_icons: ^0.0.1
  flutter_native_splash: ^2.4.6
#  hive_generator: ^2.0.0

  # Linters & Validators
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/splash_white.png
    - lib/assets/satsails.png
    - lib/assets/satsails_start_screen.png
    - lib/assets/bitrefill.png
    - lib/assets/arbitrum-logo.png
    - lib/assets/satsails.svg
    - lib/assets/logo-spark.svg
    - lib/assets/depix.png
    - lib/assets/eurx.png
    - lib/assets/l-btc.png
    - lib/assets/tether.png
    - lib/assets/bitcoin-logo.png
    - lib/assets/Bitcoin_lightning_logo.png
    - lib/assets/bip39_english.txt
    - .env
    - lib/assets/usdt.svg
    - lib/assets/usdc.svg
    - lib/assets/trx.svg
    - lib/assets/bnb.svg
    - lib/assets/sol.svg
    - lib/assets/eth.svg
    - lib/assets/pol.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "lib/assets/satsails.png"
  image_path_ios: "lib/assets/satsails_ios.png"

android_notification_icons:
  image_path: 'lib/assets/satsails.png'
  icon_name: 'ic_notification'

flutter_native_splash:
  color: "#000000"
  image: "lib/assets/splash_white.png"
  web: false
  android_12:
    color: "#000000"
    image: "lib/assets/splash_white.png"
