import 'dart:convert';
import 'package:Satsails/handlers/response_handlers.dart';
import 'package:Satsails/validations/address_validation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive/hive.dart';
import 'package:http/http.dart' as http;

class AffiliateModel extends StateNotifier<Affiliate> {
  AffiliateModel(super.state);

  Future<void> setAffiliateCode(String affiliateCode) async {
    final box = await Hive.openBox('affiliate');
    box.put('affiliateCode', affiliateCode);
    state = state.copyWith(code: affiliateCode);
  }

  Future<void> setLiquidAddress(String liquidAddress) async {
    final box = await Hive.openBox('affiliate');
    box.put('liquidAddress', liquidAddress);
    state = state.copyWith(liquidAddress: liquidAddress);
  }
}

class Affiliate {
  final String code;
  final String liquidAddress;

  Affiliate({
    required this.code,
    required this.liquidAddress,
  });

  Affiliate copyWith({
    String? code,
    String? liquidAddress,
  }) {
    return Affiliate(
      code: code ?? this.code,
      liquidAddress: liquidAddress ?? this.liquidAddress,
    );
  }

  factory Affiliate.fromJson(Map<String, dynamic> json) {
    return Affiliate(
      code: json['code'],
      liquidAddress: json['liquidAddress'],
    );
  }
}


class AffiliateService {
  static Future<Result<bool>> addAffiliateCode(String paymentId, String affiliateCode, String auth) async {
    try {
      final response = await http.post(
        Uri.parse('https://e80a-109-50-157-141.ngrok-free.app/add_affiliate'),
        body: jsonEncode({
          'user': {
            'payment_id': paymentId,
            'affiliate_code': affiliateCode,
          }
        }),
        headers: {
          'Content-Type': 'application/json',
          'Authorization': auth,
        },
      );

      if (response.statusCode == 200) {
        return Result(data: true);
      } else {
        String errorMsg = jsonDecode(response.body)['error'] ?? 'Failed to add affiliate code';
        return Result(error: errorMsg);
      }
    } catch (e) {
      return Result(error: 'An error occurred: $e');
    }
  }

  static Future<Result<bool>> createAffiliateCode(String paymentId, String affiliateCode, String liquidAddress, String auth) async {
    bool isValid = await isValidLiquidAddress(liquidAddress);
    if (isValid) {
      try {
        final response = await http.post(
          Uri.parse('https://e80a-109-50-157-141.ngrok-free.app/affiliates'),
          body: jsonEncode({
            'affiliate': {
              'affiliate_owner': paymentId,
              'code': affiliateCode,
              'liquid_address': liquidAddress,
            }
          }),
          headers: {
            'Content-Type': 'application/json',
            'Authorization': auth,
          },
        );

        if (response.statusCode == 201) {
          return Result(data: true);
        } else {
          String errorMsg = jsonDecode(response.body)['code'] ?? 'Failed to create affiliate code';
          return Result(error: errorMsg);
        }
      } catch (e) {
        return Result(error: 'An error occurred: $e');
      }
    } else {
      return Result(error: 'Invalid liquid address');
    }
  }

  static Future<Result<int>> affiliateNumberOfUsers(String affiliateCode, String auth) async {
    try {
      final uri = Uri.parse('https://e80a-109-50-157-141.ngrok-free.app/number_of_users')
          .replace(queryParameters: {
        'code': affiliateCode,
      });

      final response = await http.get(
        uri,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': auth,
        },
      );

      if (response.statusCode == 200) {
        return Result(data: jsonDecode(response.body));
      } else {
        return Result(error: 'Failed to get number of users');
      }
    } catch (e) {
      return Result(error: 'An error occurred: $e');
    }
  }

  static Future<Result<String>> affiliateEarnings(String affiliateCode, String auth) async {
    try {
      final uri = Uri.parse('https://e80a-109-50-157-141.ngrok-free.app/value_earned_by_affiliate')
          .replace(queryParameters: {
        'code': affiliateCode,
      });

      final response = await http.get(
        uri,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': auth,
        },
      );

      if (response.statusCode == 200) {
        return Result(data: jsonDecode(response.body));
      } else {
        return Result(error: 'Failed to get amount generated by affiliate');
      }
    } catch (e) {
      return Result(error: 'An error occurred: $e');
    }
  }

  static Future<Result<String>> affiliateUsersSpend(String affiliateCode, String auth) async {
    try {
      final uri = Uri.parse('https://e80a-109-50-157-141.ngrok-free.app/total_value_purchased_by_clients')
          .replace(queryParameters: {
        'code': affiliateCode,
      });

      final response = await http.get(
        uri,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': auth,
        },
      );

      if (response.statusCode == 200) {
        return Result(data: jsonDecode(response.body));
      } else {
        return Result(error: 'Failed to get amount generated by affiliate');
      }
    } catch (e) {
      return Result(error: 'An error occurred: $e');
    }
  }
  static Future<Result<List<dynamic>>> getAllTransfersFromAffiliateUsers(String affiliateCode, String auth) async {
    try {
      final response = await http.get(
        Uri.parse('https://e80a-109-50-157-141.ngrok-free.app/all_transfers')
            .replace(queryParameters: {
          'code': affiliateCode,
        }),
        headers: {
          'Content-Type': 'application/json',
          'Authorization': auth,
        },
      );

      if (response.statusCode == 200) {
        return Result(data: jsonDecode(response.body));
      } else {
        return Result(error: 'Failed to get all transfers');
      }
    } catch (e) {
      return Result(error: 'An error occurred: $e');
    }
  }
}