// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:Satsails/models/balance_model.dart';
import 'package:Satsails/models/eulen_transfer_model.dart';
import 'package:Satsails/models/nox_transfer_model.dart';
import 'package:Satsails/models/sideshift_model.dart';
import 'package:Satsails/models/sideswap/sideswap_exchange_model.dart';
import 'package:Satsails/models/sideswap/sideswap_peg_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(EulenTransferAdapter());
    registerAdapter(NoxTransferAdapter());
    registerAdapter(SideShiftAdapter());
    registerAdapter(SideswapCompletedSwapAdapter());
    registerAdapter(SideswapPegAdapter());
    registerAdapter(SideswapPegStatusAdapter());
    registerAdapter(SideswapPegStatusTransactionAdapter());
    registerAdapter(WalletBalanceAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(EulenTransferAdapter());
    registerAdapter(NoxTransferAdapter());
    registerAdapter(SideShiftAdapter());
    registerAdapter(SideswapCompletedSwapAdapter());
    registerAdapter(SideswapPegAdapter());
    registerAdapter(SideswapPegStatusAdapter());
    registerAdapter(SideswapPegStatusTransactionAdapter());
    registerAdapter(WalletBalanceAdapter());
  }
}
